apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmybuckets.dkcs.me
spec:
  group: dkcs.me
  names:
    kind: XMyBucket
    plural: xmybuckets
  claimNames:
    kind: MyBucket
    plural: mybuckets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        required: 
          - "spec"
        properties: 
          spec: 
            required: 
              - "location"
            properties: 
              location: 
                type: "string"
            type: "object"
